spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./h2db/sample
      driver-class-name: org.h2.Driver
      pool-name: hikari
      username: hsy
      password: 1234
      maximum-pool-size: 5
      minimum-idle: 1